name: Lint+Test+Build

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint:
    name: Lint files
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-go@v2
        with:
          go-version: "1.16.8"
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v2.5.2
        with:
          version: latest

  test:
    name: Run tests
    runs-on: "ubuntu-latest"
    needs: lint
    steps:
      - uses: actions/checkout@v2.3.4
      - uses: actions/setup-go@v2
        with:
          go-version: "1.16.8"
      - run: go test -race -timeout="3m" ./...

      - name: Build
        run: go build -v ./...
